name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
